service: fruit-fusion-backend

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    USERPOOLID: ${env:USERPOOLID}
    REGION: ${env:REGION}
  apiGateway:
    apiKeys:
      - ${env:API_KEY}

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: /user
          method: put
          private: true
          cors: true

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: /user/{id}
          method: get
          private: true
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: /user/{id}
          method: patch
          private: true
          cors: true

  getLeaders:
    handler: handler.getLeaders
    events:
      - http:
          path: /leaders
          method: get
          private: true
          cors: true

  getRank:
    handler: handler.getRank
    events:
      - http:
          path: /rank/{id}
          method: get
          private: true
          cors: true

  getGame:
    handler: handler.getGame
    events:
      - http:
          path: /game/{id}
          method: get
          private: true
          cors: true

  updateGame:
    handler: handler.updateGame
    events:
      - http:
          path: /game/{id}
          method: patch
          private: true
          cors: true

plugins:
  - serverless-offline
